from typing import Protocol, runtime_checkable


@runtime_checkable
class SandboxBackend(Protocol):
    """Interface for sandbox execution backends (Docker, Firecracker, etc.)."""

    def create(self) -> str: ...

    def exec(self, vm_id: str, command: str, timeout: int = 30) -> dict: ...

    def copy_to(self, vm_id: str, local_path: str, remote_path: str) -> None: ...

    def copy_from(self, vm_id: str, remote_path: str) -> bytes: ...

    def list_files(self, vm_id: str, path: str = "/workspace") -> list[str]: ...

    def destroy(self, vm_id: str) -> None: ...

    def is_running(self, vm_id: str) -> bool: ...

    @property
    def recyclable(self) -> bool: ...
